fix: update README.md file to list explicit secure practices to apply
Update README.md to explicitly list secure practices for updating GItHub
Actions taken from GitHub security documentation and examples from a few
security blogs.

When GeoNet migrated to GitHub Actions it was noted at the time to use
the full-length commit SHA value to securely use external 3rd-party code
to avoid the sort of supply chain attaks seen with Trivy scanner and
malicious overwriting of all version tags for Trivy scanner GitHub actions.

diff --git a/.github/workflows/presubmit-workflow-lint.yml b/.github/workflows/presubmit-workflow-lint.yml
--- a/.github/workflows/presubmit-workflow-lint.yml
+++ b/.github/workflows/presubmit-workflow-lint.yml
@@ -37,8 +37,8 @@ jobs:
         run: |
           FAILURES=false
           for WORKFLOW in $(find .github/workflows -name 'reusable*' | xargs); do
-            if ! grep -q "$WORKFLOW" README.md; then
-              echo "Not found in README: $WORKFLOW"
+            if ! grep -q "$WORKFLOW" USAGE.md; then
+              echo "Not found in USAGE.md: $WORKFLOW"
               FAILURES=true
             fi
           done
